# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movie_actors', through='movies.Role', to='movies.Person'),
        ),
    ]
