# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170116_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_actors', through='movies.Role', to='movies.Person'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_director', to='movies.Person'),
        ),
    ]
