# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20170116_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
